# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robocup_extension.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='robocup_extension.proto',
  package='robocup.humanoid',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17robocup_extension.proto\x12\x10robocup.humanoid\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1d\n\x05\x66vec2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"(\n\x05\x66vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"s\n\x05\x66mat3\x12\"\n\x01x\x18\x01 \x01(\x0b\x32\x17.robocup.humanoid.fvec3\x12\"\n\x01y\x18\x02 \x01(\x0b\x32\x17.robocup.humanoid.fvec3\x12\"\n\x01z\x18\x03 \x01(\x0b\x32\x17.robocup.humanoid.fvec3\"\x98\x01\n\x05Robot\x12\x11\n\tplayer_id\x18\x01 \x01(\r\x12)\n\x08position\x18\x02 \x01(\x0b\x32\x17.robocup.humanoid.fvec3\x12+\n\ncovariance\x18\x03 \x01(\x0b\x32\x17.robocup.humanoid.fmat3\x12$\n\x04team\x18\x04 \x01(\x0e\x32\x16.robocup.humanoid.Team\"\x89\x01\n\x04\x42\x61ll\x12)\n\x08position\x18\x01 \x01(\x0b\x32\x17.robocup.humanoid.fvec3\x12)\n\x08velocity\x18\x02 \x01(\x0b\x32\x17.robocup.humanoid.fvec3\x12+\n\ncovariance\x18\x03 \x01(\x0b\x32\x17.robocup.humanoid.fmat3\"\x84\x03\n\x07Message\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x05state\x18\x02 \x01(\x0e\x32\x17.robocup.humanoid.State\x12-\n\x0c\x63urrent_pose\x18\x03 \x01(\x0b\x32\x17.robocup.humanoid.Robot\x12-\n\x0cwalk_command\x18\x04 \x01(\x0b\x32\x17.robocup.humanoid.fvec3\x12,\n\x0btarget_pose\x18\x05 \x01(\x0b\x32\x17.robocup.humanoid.Robot\x12,\n\x0bkick_target\x18\x06 \x01(\x0b\x32\x17.robocup.humanoid.fvec2\x12$\n\x04\x62\x61ll\x18\x07 \x01(\x0b\x32\x16.robocup.humanoid.Ball\x12\'\n\x06others\x18\x08 \x03(\x0b\x32\x17.robocup.humanoid.Robot\x12\x19\n\x11max_walking_speed\x18\x65 \x01(\x02*+\n\x04Team\x12\x10\n\x0cUNKNOWN_TEAM\x10\x00\x12\x08\n\x04\x42LUE\x10\x01\x12\x07\n\x03RED\x10\x02*:\n\x05State\x12\x11\n\rUNKNOWN_STATE\x10\x00\x12\x0f\n\x0bUNPENALISED\x10\x01\x12\r\n\tPENALISED\x10\x02\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_TEAM = _descriptor.EnumDescriptor(
  name='Team',
  full_name='robocup.humanoid.Team',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TEAM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=954,
  serialized_end=997,
)
_sym_db.RegisterEnumDescriptor(_TEAM)

Team = enum_type_wrapper.EnumTypeWrapper(_TEAM)
_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='robocup.humanoid.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_STATE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNPENALISED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PENALISED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=999,
  serialized_end=1057,
)
_sym_db.RegisterEnumDescriptor(_STATE)

State = enum_type_wrapper.EnumTypeWrapper(_STATE)
UNKNOWN_TEAM = 0
BLUE = 1
RED = 2
UNKNOWN_STATE = 0
UNPENALISED = 1
PENALISED = 2



_FVEC2 = _descriptor.Descriptor(
  name='fvec2',
  full_name='robocup.humanoid.fvec2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='robocup.humanoid.fvec2.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='robocup.humanoid.fvec2.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=107,
)


_FVEC3 = _descriptor.Descriptor(
  name='fvec3',
  full_name='robocup.humanoid.fvec3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='robocup.humanoid.fvec3.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='robocup.humanoid.fvec3.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='robocup.humanoid.fvec3.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=149,
)


_FMAT3 = _descriptor.Descriptor(
  name='fmat3',
  full_name='robocup.humanoid.fmat3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='robocup.humanoid.fmat3.x', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='robocup.humanoid.fmat3.y', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='robocup.humanoid.fmat3.z', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=266,
)


_ROBOT = _descriptor.Descriptor(
  name='Robot',
  full_name='robocup.humanoid.Robot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='robocup.humanoid.Robot.player_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='robocup.humanoid.Robot.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='robocup.humanoid.Robot.covariance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team', full_name='robocup.humanoid.Robot.team', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=421,
)


_BALL = _descriptor.Descriptor(
  name='Ball',
  full_name='robocup.humanoid.Ball',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='robocup.humanoid.Ball.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='robocup.humanoid.Ball.velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='robocup.humanoid.Ball.covariance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=561,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='robocup.humanoid.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='robocup.humanoid.Message.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='robocup.humanoid.Message.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_pose', full_name='robocup.humanoid.Message.current_pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='walk_command', full_name='robocup.humanoid.Message.walk_command', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_pose', full_name='robocup.humanoid.Message.target_pose', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kick_target', full_name='robocup.humanoid.Message.kick_target', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ball', full_name='robocup.humanoid.Message.ball', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='others', full_name='robocup.humanoid.Message.others', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_walking_speed', full_name='robocup.humanoid.Message.max_walking_speed', index=8,
      number=101, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=564,
  serialized_end=952,
)

_FMAT3.fields_by_name['x'].message_type = _FVEC3
_FMAT3.fields_by_name['y'].message_type = _FVEC3
_FMAT3.fields_by_name['z'].message_type = _FVEC3
_ROBOT.fields_by_name['position'].message_type = _FVEC3
_ROBOT.fields_by_name['covariance'].message_type = _FMAT3
_ROBOT.fields_by_name['team'].enum_type = _TEAM
_BALL.fields_by_name['position'].message_type = _FVEC3
_BALL.fields_by_name['velocity'].message_type = _FVEC3
_BALL.fields_by_name['covariance'].message_type = _FMAT3
_MESSAGE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_MESSAGE.fields_by_name['state'].enum_type = _STATE
_MESSAGE.fields_by_name['current_pose'].message_type = _ROBOT
_MESSAGE.fields_by_name['walk_command'].message_type = _FVEC3
_MESSAGE.fields_by_name['target_pose'].message_type = _ROBOT
_MESSAGE.fields_by_name['kick_target'].message_type = _FVEC2
_MESSAGE.fields_by_name['ball'].message_type = _BALL
_MESSAGE.fields_by_name['others'].message_type = _ROBOT
DESCRIPTOR.message_types_by_name['fvec2'] = _FVEC2
DESCRIPTOR.message_types_by_name['fvec3'] = _FVEC3
DESCRIPTOR.message_types_by_name['fmat3'] = _FMAT3
DESCRIPTOR.message_types_by_name['Robot'] = _ROBOT
DESCRIPTOR.message_types_by_name['Ball'] = _BALL
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.enum_types_by_name['Team'] = _TEAM
DESCRIPTOR.enum_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

fvec2 = _reflection.GeneratedProtocolMessageType('fvec2', (_message.Message,), dict(
  DESCRIPTOR = _FVEC2,
  __module__ = 'robocup_extension_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.fvec2)
  ))
_sym_db.RegisterMessage(fvec2)

fvec3 = _reflection.GeneratedProtocolMessageType('fvec3', (_message.Message,), dict(
  DESCRIPTOR = _FVEC3,
  __module__ = 'robocup_extension_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.fvec3)
  ))
_sym_db.RegisterMessage(fvec3)

fmat3 = _reflection.GeneratedProtocolMessageType('fmat3', (_message.Message,), dict(
  DESCRIPTOR = _FMAT3,
  __module__ = 'robocup_extension_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.fmat3)
  ))
_sym_db.RegisterMessage(fmat3)

Robot = _reflection.GeneratedProtocolMessageType('Robot', (_message.Message,), dict(
  DESCRIPTOR = _ROBOT,
  __module__ = 'robocup_extension_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.Robot)
  ))
_sym_db.RegisterMessage(Robot)

Ball = _reflection.GeneratedProtocolMessageType('Ball', (_message.Message,), dict(
  DESCRIPTOR = _BALL,
  __module__ = 'robocup_extension_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.Ball)
  ))
_sym_db.RegisterMessage(Ball)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'robocup_extension_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
