# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_state.proto',
  package='robocup.humanoid',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11robot_state.proto\x12\x10robocup.humanoid\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1d\n\x05\x66vec2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"(\n\x05\x66vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"3\n\x05\x66vec4\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"a\n\x06Pose3D\x12)\n\x08position\x18\x01 \x01(\x0b\x32\x17.robocup.humanoid.fvec3\x12,\n\x0borientation\x18\x02 \x01(\x0b\x32\x17.robocup.humanoid.fvec4\"-\n\x06Pose2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05theta\x18\x03 \x01(\x02\"\xf0\x01\n\x07Message\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tplayer_id\x18\x02 \x01(\r\x12(\n\x06status\x18\x03 \x01(\x0e\x32\x18.robocup.humanoid.Status\x12$\n\x04role\x18\x04 \x01(\x0e\x32\x16.robocup.humanoid.Role\x12&\n\x04pose\x18\x05 \x01(\x0b\x32\x18.robocup.humanoid.Pose3D\x12+\n\tball_pose\x18\x06 \x01(\x0b\x32\x18.robocup.humanoid.Pose2D*\xda\x02\n\x06Status\x12\x17\n\x13STATUS_DISCONNECTED\x10\x00\x12\x10\n\x0cSTATUS_READY\x10\x01\x12\x15\n\x11STATUS_LOCALIZING\x10\x02\x12\x12\n\x0eSTATUS_WALKING\x10\x03\x12\x1b\n\x17STATUS_TERMINATING_WALK\x10\x04\x12\x12\n\x0eSTATUS_KICKING\x10\x05\x12\x17\n\x13STATUS_FALLEN_FRONT\x10\x06\x12\x16\n\x12STATUS_FALLEN_BACK\x10\x07\x12\x16\n\x12STATUS_FALLEN_SIDE\x10\x08\x12\x12\n\x0eSTATUS_PENALTY\x10\t\x12\x18\n\x14STATUS_OUT_OF_BOUNDS\x10\n\x12!\n\x1dSTATUS_TRAJECTORY_IN_PROGRESS\x10\x0b\x12\x12\n\x0eSTATUS_STOPPED\x10\x0c\x12\x1b\n\x17STATUS_DETERMINING_SIDE\x10\r*g\n\x04Role\x12\x13\n\x0fROLE_UNASSIGNED\x10\x00\x12\x0f\n\x0bROLE_GOALIE\x10\x01\x12\x10\n\x0cROLE_STRIKER\x10\x02\x12\x12\n\x0eROLE_LEFT_WING\x10\x03\x12\x13\n\x0fROLE_RIGHT_WING\x10\x04\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='robocup.humanoid.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATUS_DISCONNECTED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_READY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_LOCALIZING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_WALKING', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_TERMINATING_WALK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_KICKING', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_FALLEN_FRONT', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_FALLEN_BACK', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_FALLEN_SIDE', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_PENALTY', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_OUT_OF_BOUNDS', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_TRAJECTORY_IN_PROGRESS', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_STOPPED', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_DETERMINING_SIDE', index=13, number=13,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=588,
  serialized_end=934,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='robocup.humanoid.Role',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ROLE_UNASSIGNED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROLE_GOALIE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROLE_STRIKER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROLE_LEFT_WING', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROLE_RIGHT_WING', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=936,
  serialized_end=1039,
)
_sym_db.RegisterEnumDescriptor(_ROLE)

Role = enum_type_wrapper.EnumTypeWrapper(_ROLE)
STATUS_DISCONNECTED = 0
STATUS_READY = 1
STATUS_LOCALIZING = 2
STATUS_WALKING = 3
STATUS_TERMINATING_WALK = 4
STATUS_KICKING = 5
STATUS_FALLEN_FRONT = 6
STATUS_FALLEN_BACK = 7
STATUS_FALLEN_SIDE = 8
STATUS_PENALTY = 9
STATUS_OUT_OF_BOUNDS = 10
STATUS_TRAJECTORY_IN_PROGRESS = 11
STATUS_STOPPED = 12
STATUS_DETERMINING_SIDE = 13
ROLE_UNASSIGNED = 0
ROLE_GOALIE = 1
ROLE_STRIKER = 2
ROLE_LEFT_WING = 3
ROLE_RIGHT_WING = 4



_FVEC2 = _descriptor.Descriptor(
  name='fvec2',
  full_name='robocup.humanoid.fvec2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='robocup.humanoid.fvec2.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='robocup.humanoid.fvec2.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=101,
)


_FVEC3 = _descriptor.Descriptor(
  name='fvec3',
  full_name='robocup.humanoid.fvec3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='robocup.humanoid.fvec3.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='robocup.humanoid.fvec3.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='robocup.humanoid.fvec3.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=143,
)


_FVEC4 = _descriptor.Descriptor(
  name='fvec4',
  full_name='robocup.humanoid.fvec4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='robocup.humanoid.fvec4.w', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='robocup.humanoid.fvec4.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='robocup.humanoid.fvec4.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='robocup.humanoid.fvec4.z', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=196,
)


_POSE3D = _descriptor.Descriptor(
  name='Pose3D',
  full_name='robocup.humanoid.Pose3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='robocup.humanoid.Pose3D.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='robocup.humanoid.Pose3D.orientation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=295,
)


_POSE2D = _descriptor.Descriptor(
  name='Pose2D',
  full_name='robocup.humanoid.Pose2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='robocup.humanoid.Pose2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='robocup.humanoid.Pose2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theta', full_name='robocup.humanoid.Pose2D.theta', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=342,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='robocup.humanoid.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='robocup.humanoid.Message.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='robocup.humanoid.Message.player_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='robocup.humanoid.Message.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='robocup.humanoid.Message.role', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='robocup.humanoid.Message.pose', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ball_pose', full_name='robocup.humanoid.Message.ball_pose', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=585,
)

_POSE3D.fields_by_name['position'].message_type = _FVEC3
_POSE3D.fields_by_name['orientation'].message_type = _FVEC4
_MESSAGE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_MESSAGE.fields_by_name['status'].enum_type = _STATUS
_MESSAGE.fields_by_name['role'].enum_type = _ROLE
_MESSAGE.fields_by_name['pose'].message_type = _POSE3D
_MESSAGE.fields_by_name['ball_pose'].message_type = _POSE2D
DESCRIPTOR.message_types_by_name['fvec2'] = _FVEC2
DESCRIPTOR.message_types_by_name['fvec3'] = _FVEC3
DESCRIPTOR.message_types_by_name['fvec4'] = _FVEC4
DESCRIPTOR.message_types_by_name['Pose3D'] = _POSE3D
DESCRIPTOR.message_types_by_name['Pose2D'] = _POSE2D
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['Role'] = _ROLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

fvec2 = _reflection.GeneratedProtocolMessageType('fvec2', (_message.Message,), dict(
  DESCRIPTOR = _FVEC2,
  __module__ = 'robot_state_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.fvec2)
  ))
_sym_db.RegisterMessage(fvec2)

fvec3 = _reflection.GeneratedProtocolMessageType('fvec3', (_message.Message,), dict(
  DESCRIPTOR = _FVEC3,
  __module__ = 'robot_state_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.fvec3)
  ))
_sym_db.RegisterMessage(fvec3)

fvec4 = _reflection.GeneratedProtocolMessageType('fvec4', (_message.Message,), dict(
  DESCRIPTOR = _FVEC4,
  __module__ = 'robot_state_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.fvec4)
  ))
_sym_db.RegisterMessage(fvec4)

Pose3D = _reflection.GeneratedProtocolMessageType('Pose3D', (_message.Message,), dict(
  DESCRIPTOR = _POSE3D,
  __module__ = 'robot_state_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.Pose3D)
  ))
_sym_db.RegisterMessage(Pose3D)

Pose2D = _reflection.GeneratedProtocolMessageType('Pose2D', (_message.Message,), dict(
  DESCRIPTOR = _POSE2D,
  __module__ = 'robot_state_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.Pose2D)
  ))
_sym_db.RegisterMessage(Pose2D)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'robot_state_pb2'
  # @@protoc_insertion_point(class_scope:robocup.humanoid.Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
