# Exclude Regex https://www3.ntu.edu.sg/home/ehchua/programming/howto/Regexe.html#zz-1.8
x-exclude: &exclude
  exclude: ^(external\/|cmake-build-debug\/|.pytest_cache\/|soccer_embedded\/|docs\/|.idea\/|.+pb2\.py\/|bez2_description\/|scripts\/|modify_proto.py\/|bez1_description\/|scripts\/|modify_proto.py)

  py:
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-symlinks
        <<: *exclude
      - id: end-of-file-fixer
        <<: *exclude
      - id: trailing-whitespace
        <<: *exclude
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        <<: *exclude
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        <<: *exclude
        args:
          - --line-length=150
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
        args:
          - --profile
          - black
        <<: *exclude
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        <<: *exclude
        args:
          - --max-line-length=150
          - --max-complexity=40
          - --select=B,C,E,F,W,T4,B9
          - --ignore=E203,E266,E501,W503,F403,F401,E402,BLK100,F405,E722,E712,E741,F841,E731
        additional_dependencies:
          - flake8-black>=0.3.2
        language_version: python3
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        <<: *exclude
        additional_dependencies:
          - pyyaml
