# Exclude Regex https://www3.ntu.edu.sg/home/ehchua/programming/howto/Regexe.html#zz-1.8
x-exclude: &exclude
  exclude: '^(external|cmake-build-debug|.pytest_cache|docs|.idea|.+pb2.py|soccer_description|soccer_hardware/soccer_firmware|soccerbot/rviz/RoboSoccer.json)'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-symlinks
        <<: *exclude
      - id: end-of-file-fixer
        <<: *exclude
      - id: trailing-whitespace
        <<: *exclude
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        <<: *exclude
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        <<: *exclude
        args:
          - --line-length=150
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        args:
          - --profile
          - black
        <<: *exclude
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        <<: *exclude
        args:
          - --max-line-length=150
          - --max-complexity=40
          - --select=B,C,E,F,W,T4,B9
          - --ignore=E203,E266,E501,W503,F403,F401,E402,BLK100,F405,E722,E712,E741,F841,E731
        additional_dependencies:
          - flake8-black>=0.3.2
        language_version: python3
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        <<: *exclude
        additional_dependencies:
          - pyyaml
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: ''  # Use the sha / tag you want to point at
#    hooks:
#      - id: mypy
#        exclude: "cmake-build-debug|setup.py|external"
#        args: ["--config-file","pyproject.toml"]
