x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu, compute, utility, graphics]

services:
  simulator:
    <<: *gpu
    network_mode: host
    extends:
      file: tools/docker/compose.simulation.yaml
      service: simulator

  soccerbot_no_cuda:
    network_mode: host
    extends:
      file: tools/docker/compose.autonomy.yaml
      service: soccerbot_no_cuda

  soccerbot:
    <<: *gpu
    network_mode: host
    extends:
      file: tools/docker/compose.autonomy.yaml
      service: soccerbot

  soccerbot_arm64:
    extends:
      file: tools/docker/compose.autonomy_arm64.yaml
      service: soccerbot_arm64
#  soccerbot_test:
#    extends:
#      file: tools/docker/compose.testing.yaml
#      service: soccerbot_test
#
#  simulator_test:
#    extends:
#      file: tools/docker/compose.testing.yaml
#      service: simulator
