version: "3.3"

services:
  friendly:
    ports:
      - 11311:11311
  opponent:
    ports:
      - 11312:11311
    command: "echo 'Opponent is manually disabled in docker-compose.override.yaml file'"
