version: "3.3"

networks:
  soccer_network:
    ipam:
      config:
        - subnet: 172.18.0.0/24

services:
  simulator:
    extends:
      file: docker-compose.yaml
      service: simulator
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw
      - /dev/snd:/dev/snd:rw
      - ./external/hlvs_webots/controllers/referee/team_1_double.json:/usr/local/hlvs_webots/controllers/referee/team_1_single_bez1.json:rw
      - ./external/hlvs_webots/controllers/referee/team_2_empty.json:/usr/local/hlvs_webots/controllers/referee/team_2_single_bez1.json:rw
      - ./external/hlvs_webots/protos/:/usr/local/hlvs_webots/protos/:rw
    environment:
      TEAM_1_PLAYERS_ON_FIELD: "1,2"
      TEAM_2_PLAYERS_ON_FIELD: ""
  friendly1:
    extends:
      file: docker-compose.yaml
      service: friendly
    networks:
      soccer_network:
        ipv4_address: 172.18.0.2
    environment:
      ROBOCUP_ROBOT_ID: 1
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10001"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_TEAM_ID: 16
      PYTHONUNBUFFERED: 1

  friendly2: # Left midfield
    extends:
      file: docker-compose.yaml
      service: friendly
    networks:
      soccer_network:
        ipv4_address: 172.18.0.3
    environment:
      ROBOCUP_ROBOT_ID: 2
      ROBOCUP_TEAM_ID: 16
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10002"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      PYTHONUNBUFFERED: 1
