left_leg_motor_0:
  id: 4
  type: "xm430"
  angle_zero: 180
  angle_max: 360
  angle_min: 0

left_leg_motor_1:
  id: 5
  type: "xm430"
  angle_zero: 180
  angle_max: 360
  angle_min: 0
  flipped: "true"

left_leg_motor_2:
  id: 6
  type: "xm430"
  angle_zero: 180
  angle_max: 360
  angle_min: 0
  flipped: "true"

left_leg_motor_3:
  id: 7
  type: "mx64"
  angle_zero: 270
  angle_max: 360
  angle_min: 0

left_leg_motor_4:
  id: 8
  type: "mx64"
  angle_zero: 180
  angle_max: 360
  angle_min: 0

left_leg_motor_5:
  id: 9
  type: "mx64"
  angle_zero: 180
  angle_max: 360
  angle_min: 0
  flipped: "true"

right_leg_motor_0:
  id: 10
  type: "xm430"
  angle_zero: 180
  angle_max: 360
  angle_min: 0
  flipped: "true"

right_leg_motor_1:
  id: 11
  type: "xm430"
  angle_zero: 180
  angle_max: 360
  angle_min: 0

right_leg_motor_2:
  id: 12
  type: "xm430"
  angle_zero: 180
  angle_max: 360
  angle_min: 0

right_leg_motor_3:
  id: 13
  type: "mx64"
  angle_zero: 90
  angle_max: 360
  angle_min: 0
  flipped: "true"

right_leg_motor_4:
  id: 14
  type: "mx64"
  angle_zero: 180
  angle_max: 360
  angle_min: 0
  flipped: "true"

right_leg_motor_5:
  id: 15
  type: "mx64"
  angle_zero: 180
  angle_max: 360
  angle_min: 0

left_arm_motor_0:
  id: 18
  type: "mx28"
  angle_zero: 180
  angle_max: 360
  angle_min: 0
  flipped: "true"

left_arm_motor_1:
  id: 0
  type: "mx28"
  angle_zero: 180
  angle_max: 360
  angle_min: 0

left_arm_motor_2:
  id: 1
  type: "mx28"
  angle_zero: 180
  angle_max: 360
  angle_min: 0
  flipped: "true"

right_arm_motor_0: # Checked
  id: 19
  type: "mx28"
  angle_zero: 180
  angle_max: 360
  angle_min: 0

right_arm_motor_1:
  id: 2
  type: "mx28"
  angle_zero: 180
  angle_max: 360
  angle_min: 0
  flipped: "true"

right_arm_motor_2:
  id: 3
  type: "mx28"
  angle_zero: 180
  angle_max: 360
  angle_min: 0

head_motor_0:
  id: 16
  type: "xl430"
  angle_zero: 180
  angle_max: 360
  angle_min: 0
  flipped: "true"

head_motor_1:
  id: 17
  type: "xl430"
  angle_zero: 180
  angle_max: 360
  angle_min: 0
