z: 0.36
orientation:
  x: 0.0
  y: 0.0
  z: 0.0
  w: 1.0

right_leg_motor_0: 0.0
right_leg_motor_1: -0.05
right_leg_motor_2: 0.25
right_leg_motor_3: -0.4
right_leg_motor_4: 0.2
right_leg_motor_5: 0.05

left_leg_motor_0: 0.0
left_leg_motor_1: 0.05
left_leg_motor_2: 0.25
left_leg_motor_3: -0.4
left_leg_motor_4: 0.2
left_leg_motor_5: -0.05

head_motor_0: 0.0
head_motor_1: 0.0

left_arm_motor_0: 0.2
left_arm_motor_1: 0.0
right_arm_motor_0: 0.2
right_arm_motor_1: 0.0