ROBOCUP_ROBOT_ID: 3
ROBOCUP_TEAM_COLOR: red
ROBOCUP_SIMULATOR_ADDR: 127.0.0.1:10003
ROBOCUP_MIRROR_SERVER_IP: 127.0.0.1
ROBOCUP_GAMECONTROLLER_IP: 127.0.1.1
X_POS: 4
Y_POS: 3.06
ANGLE: 1.57
ROBOT_NAME: robot3
COMPETITION: true
GOALIE: true
ENABLE_PYBULLET: false
TEAM_ID: 16
