function De = calc_De(i1,i2,l1,lc1,lc2,m1,m2,q1,q2)
%CALC_DE
%    DE = CALC_DE(I1,I2,L1,LC1,LC2,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    14-Jun-2022 22:36:21

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = m1+m2;
t6 = q1+q2;
t7 = l1.^2;
t8 = lc2.^2;
t11 = -lc1;
t9 = cos(t6);
t10 = sin(t6);
t12 = m2.*t8;
t13 = l1.*lc2.*m2.*t3;
t14 = l1+t11;
t15 = lc2.*m2.*t9;
t16 = lc2.*m2.*t10;
t18 = i2+t12+t13;
t17 = -t16;
De = reshape([i1+t13+t18+m1.*t7+m2.*t7+lc1.^2.*m1-l1.*lc1.*m1.*2.0,t18,m2.*(l1.*t4.*2.0+lc2.*t10.*2.0).*(-1.0./2.0)-m1.*t4.*t14,(m2.*(l1.*t2.*2.0+lc2.*t9.*2.0))./2.0+m1.*t2.*t14,t18,i2+t12,t17,t15,t17-l1.*m1.*t4-l1.*m2.*t4+lc1.*m1.*t4,t17,t5,0.0,t15+l1.*m1.*t2+l1.*m2.*t2+m1.*t2.*t11,t15,0.0,t5],[4,4]);
