from gym_soccerbot.envs.walking_forward_env import WalkingForward
from gym_soccerbot.envs.walking_forward_env_1 import WalkingForwardV1
from gym_soccerbot.envs.walking_forward_env_2 import WalkingForwardV2
from gym_soccerbot.envs.walking_forward_env_3 import WalkingForwardV3
from gym_soccerbot.envs.walking_forward_norm_env import WalkingForwardNorm
from gym_soccerbot.envs.walking_forward_norm_agn_env import WalkingForwardNormAgn