# Path parameters
robot_model: bez2

walking_torso_height: 0.37
steps_per_second_default: 3.0
torso_step_length: 0.08
torso_step_length_short_backwards: 0.08
torso_step_length_short_forwards: 0.08
foot_separation: 0.038
torso_offset_x_ready: -0.08 # positive is forward
torso_offset_x: -0.04
merge_fixed_links: true
foot_box: [0.09, 0.07, 0.05] # TODO: update this!
right_foot_joint_center_to_collision_box_center: [0.00385, 0.00401, -0.00737] # TODO: update this!

torso_sidediff_sway: -0.006

walking_Kp: 3.0
walking_Ki: 0.0000
walking_Kd: 10.0
walking_setpoint: 0.02

standing_Kp: 2.0
standing_Ki: 0.015
standing_Kd: 10.0
standing_setpoint: 0.0

calibration_trans_a: -0.020357517843533346
calibration_trans_b: 0.6492919423070727
calibration_trans_a2: 0.8427201135750022
calibration_rot_a: 0.7052919512780853
