# Path parameters
robot_model: bez2

walking_torso_height: 0.3
steps_per_second_default: .6
bodystep_size_default: 0.05
foot_separation: 0.04
torso_offset_x_ready: -0.06 # positive is forward
torso_offset_x: -0.02
merge_fixed_links: true
foot_box: [0.09, 0.07, 0.05] # TODO: update this!
right_foot_joint_center_to_collision_box_center: [0.00385, 0.00401, -0.00737]  # TODO: update this!

walking_Kp: 0
walking_Ki: 0.0000
walking_Kd: 0
walking_setpoint: 0.02

standing_Kp: 0
standing_Ki: 0
standing_Kd: 0
standing_setpoint: 0.0
