export const ADD_MODIFY_ROBOTS_INFO = "ADD_MODIFY_ROBOTS_INFO";
export const REMOVE_ROBOT_INFO = "REMOVE_ROBOT_INFO";
export const REMOVE_ROBOT_CONFIG = "REMOVE_ROBOT_CONFIG";

export const ADD_MODIFY_ROSMON = "ADD_MODIFY_ROSMON";
export const ADD_MODIFY_ROSOUT = "ADD_MODIFY_ROSOUT";
export const MODIFY_CMD_GLOBAL = "MODIFY_CMD_GLOBAL";

export const ADD_ROBOT_NOTIFICATION = "ADD_ROBOT_NOTIFICATION";
export const REMOVE_ROBOT_NOTIFICATION = "REMOVE_ROBOT_NOTIFICATION";

export const WATCH_ROBOTS_INFO = "WATCH_ROBOTS_INFO";
export const WATCH_CONFIG_STRING = "WATCH_CONFIG_STRING";
