services:
  soccerbot_arm64:
    network_mode: host
    extends:
      file: compose.autonomy.yaml
      service: soccerbot
    image: utrarobosoccer/soccerbot:arm64
    group_add:
      - "1001"
    build:
      context: ../../.
      dockerfile: tools/docker/Dockerfile
      target: builder
      platforms:
        - linux/arm64
      args:
        - BUILDKIT_INLINE_CACHE=1
        - BASE_IMAGE=arm64v8/ros:noetic-robot
        - ARCHITECTURE=sbsa
      cache_from:
        - utrarobosoccer/soccerbot:arm64
    volumes:
      - /run/jtop.sock:/run/jtop.sock
      - /usr/bin/tegrastats:/usr/bin/tegrastats
      - /usr/bin/nvpmodel:/usr/bin/nvpmodel
      - /usr/bin/jetson_clocks:/usr/bin/jetson_clocks
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra
      - /usr/local/cuda:/usr/local/cuda
      - /usr/local/cuda-11:/usr/local/cuda-11
      - /usr/local/cuda-11.4:/usr/local/cuda-11.4
      - /etc/alternatives/cuda:/etc/alternatives/cuda
      - /etc/alternatives/cuda-11:/etc/alternatives/cuda-11
      - /usr/lib/aarch64-linux-gnu/libcudnn.so:/usr/lib/aarch64-linux-gnu/libcudnn.so
      - /usr/lib/aarch64-linux-gnu/libcudnn.so.8:/usr/lib/aarch64-linux-gnu/libcudnn.so.8
      - /usr/lib/aarch64-linux-gnu/libcudnn.so.8.6.0:/usr/lib/aarch64-linux-gnu/libcudnn.so.8.6.0
      - /usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.6.0:/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.6.0
      - /usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.6.0:/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.6.0
      - /usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.6.0:/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
      - /usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.6.0:/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.6.0
      - /usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.6.0:/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.6.0
      - /usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.6.0:/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.6.0
      - /usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8:/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8
      - /usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8:/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8
      - /usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8:/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8
      - /usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8:/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8
      - /usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8:/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8
      - /usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8:/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8
      - /usr/lib/aarch64-linux-gnu/libcudnn_adv_infer_static.a:/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer_static.a
      - /usr/lib/aarch64-linux-gnu/libcudnn_adv_train_static.a:/usr/lib/aarch64-linux-gnu/libcudnn_adv_train_static.a
      - /usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer_static.a:/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer_static.a
      - /usr/lib/aarch64-linux-gnu/libcudnn_cnn_train_static.a:/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train_static.a
      - /usr/lib/aarch64-linux-gnu/libcudnn_ops_infer_static.a:/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer_static.a
      - /usr/lib/aarch64-linux-gnu/libcudnn_ops_train_static.a:/usr/lib/aarch64-linux-gnu/libcudnn_ops_train_static.a
      - /usr/lib/aarch64-linux-gnu/libcudnn_adv_infer_static_v8.a:/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer_static_v8.a
      - /usr/lib/aarch64-linux-gnu/libcudnn_adv_train_static_v8.a:/usr/lib/aarch64-linux-gnu/libcudnn_adv_train_static_v8.a
      - /usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer_static_v8.a:/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer_static_v8.a
      - /usr/lib/aarch64-linux-gnu/libcudnn_cnn_train_static_v8.a:/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train_static_v8.a
      - /usr/lib/aarch64-linux-gnu/libcudnn_ops_infer_static_v8.a:/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer_static_v8.a
      - /usr/lib/aarch64-linux-gnu/libcudnn_ops_train_static_v8.a:/usr/lib/aarch64-linux-gnu/libcudnn_ops_train_static_v8.a
      - /dev:/dev
      - /tmp/argus_socket:/tmp/argus_socket
      - /var/nvidia/nvcam/settings/:/var/nvidia/nvcam/settings/
      - /etc/systemd/system:/etc/systemd/system
    # Command that runs when docker compose pull is executed
    command:
      /bin/bash -c "source ~/ros2_ws/devel/setup.bash && sudo chmod +s /usr/bin/nice &&
      roslaunch soccerbot soccerbot.launch simulation:=false __ns:=robot$$ROBOCUP_ROBOT_ID || sleep infinity"
#    environment:
#      ROS_MASTER_URI: ${ROS_MASTER_URI}
#      ROS_IP: ${ROS_IP}
#      ROBOT_MODEL: ${ROBOT_MODEL:-bez1}
#      ROBOCUP_ROBOT_ID: ${ROBOCUP_ROBOT_ID:-2}
#      ROBOCUP_TEAM_COLOR: ${ROBOCUP_TEAM_COLOR:-"blue"}
#      ROBOCUP_TEAM_ID: ${ROBOCUP_TEAM_ID:-10}
#      PYTHONUNBUFFERED: 1
#      PYTHONPATH: /home/robosoccer/ros2_ws/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/home/robosoccer/.local/lib/python3.8/site-packages
