x-soccerbot: &soccerbot
  image: utrarobosoccer/soccerbot
  privileged: true
  user: "1000"
  build:
    context: ../../.
    dockerfile: tools/docker/Dockerfile
    target: builder
    args:
      - BUILDKIT_INLINE_CACHE=1
    cache_from:
      - utrarobosoccer/soccerbot
  cap_add:
    - SYS_PTRACE
    - SYS_NICE
  pid: "host"
  security_opt:
    - seccomp:unconfined
  command:
    /bin/bash -c "export ROS_MASTER_URI=http://$$(hostname -i):11311 && export ROS_IP=$$(hostname -i) &&
    bash ./src/soccerbot/soccerbot/scripts/start_competition.sh robot$$ROBOCUP_ROBOT_ID"
  volumes:
    - /home/$USER/catkin_ws/src/soccerbot:/home/robosoccer/catkin_ws/src/soccerbot
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw
    - /dev/snd:/dev/snd:rw
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev:/dev

services:
  soccerbot:
    <<: *soccerbot
    environment:
      ROBOCUP_ROBOT_ID: 1 # (see start_competition.sh for positions), not 1 https://discord.com/channels/462951096374132736/798238127588114462/954388600290685008
      ROBOT_MODEL: bez1
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10001"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      ROBOCUP_TEAM_ID: 16
      PYTHONUNBUFFERED: 1
      DISPLAY: unix$DISPLAY
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR

  soccerbot_no_cuda:
    <<: *soccerbot
    build:
      context: ../../.
      dockerfile: tools/docker/Dockerfile
      target: builder
      args:
        - BUILDKIT_INLINE_CACHE=1
        - INSTALL_CUDA=false
      cache_from:
        - utrarobosoccer/soccerbot:no_cuda
    environment:
      ROBOCUP_ROBOT_ID: 1 # (see start_competition.sh for positions), not 1 https://discord.com/channels/462951096374132736/798238127588114462/954388600290685008
      ROBOT_MODEL: bez1
      ROBOCUP_TEAM_COLOR: "red"
      ROBOCUP_SIMULATOR_ADDR: "simulator:10001"
      ROBOCUP_GAMECONTROLLER_IP: "simulator"
      ROBOCUP_MIRROR_SERVER_IP: "simulator"
      ROBOCUP_TEAM_ID: 16
      PYTHONUNBUFFERED: 1
      DISPLAY: unix$DISPLAY
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
      ZED: "false"
