x-simulator: &simulator
  image: utrarobosoccer/webots
  stop_signal: SIGINT
  stop_grace_period: 10s
  privileged: true
  build:
    context: ../../external
    args:
      - BUILDKIT_INLINE_CACHE=1
    cache_from:
      - utrarobosoccer/webots
  cap_add:
    - SYS_PTRACE
  pid: "host"
  command:
    /bin/bash -c "export ROS_MASTER_URI=http://localhost:11311 && export ROS_IP=127.0.0.1 && export PYTHONPATH=$PYTHONPATH:$WEBOTS_HOME/lib/controller/python38 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WEBOTS_HOME/lib/controller &&  source ~/catkin_ws/devel/setup.bash &&
    roslaunch soccer_webots webots.launch  __ns:=robot1 || sleep infinity"
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw
    - /dev/snd:/dev/snd:rw
    - /home/$USER/catkin_ws/src/soccerbot/external/hlvs_webots/worlds:/home/robosoccer/catkin_ws/src/soccerbot/external/hlvs_webots/worlds:rw
    - /home/$USER/catkin_ws/src/soccerbot/external/hlvs_webots/controllers/referee/:/home/robosoccer/catkin_ws/src/soccerbot/external/hlvs_webots/controllers/referee/:rw
    - /home/$USER/catkin_ws/src/soccerbot/external/hlvs_webots/protos/:/home/robosoccer/catkin_ws/src/soccerbot/external/hlvs_webots/protos/:rw
    #    - /home/$USER/catkin_ws/src/soccerbot/external/hlvs_webots/soccer_webots/:/home/robosoccer/catkin_ws/src/soccerbot/external/hlvs_webots/soccer_webots/:rw
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev:/dev

services:
  simulator:
    user: "1000"
    <<: *simulator
    environment:
      PYTHONUNBUFFERED: 1
      DISPLAY: unix$DISPLAY
      JAVA_HOME: /usr
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
      # Specify in comma seperated list see https://github.com/utra-robosoccer/hlvs_webots/blob/16194d22c91b8dfcae3b3298524281bf895cab5d/controllers/referee/team.py#L36
      TEAM_1_PLAYERS_ON_FIELD: "1"
      TEAM_2_PLAYERS_ON_FIELD: ""
      ROBOT_MODEL: "bez1"
