name: Docker Image

on:
  workflow_dispatch:
    inputs:
      use_cached_image:
        description: 'Use cached image'
        required: false
        default: true
        type: boolean
  schedule:
    - cron: "0 1 1 * *"
  push:
    branches: [master]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          df -h
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Pull original docker image
        run: |
          docker pull utrarobosoccer/soccerbot
      - name: Build the Docker image
        run: |
          docker buildx build . --file Dockerfile --tag utrarobosoccer/soccerbot --progress=plain --cache-from utrarobosoccer/soccerbot --build-arg BUILDKIT_INLINE_CACHE=1
      - name: Push Docker image to dockerhub
        run: docker push utrarobosoccer/soccerbot
#       - name: Push to AWS repository
#         run: |
#           aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 047817357099.dkr.ecr.us-east-2.amazonaws.com/hl-vs-utra
#           docker tag utrarobosoccer/soccerbot 047817357099.dkr.ecr.us-east-2.amazonaws.com/hl-vs-utra
#           docker push 047817357099.dkr.ecr.us-east-2.amazonaws.com/hl-vs-utra
