name: Docker Image Noetic

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update_ros_image:
    runs-on: ubuntu-20.04

    steps:
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the Docker image
        run: |
          docker pull ros:noetic
          docker tag ros:noetic utrarobosoccer/noetic
          docker push utrarobosoccer/noetic
