name: Docker Image

on:
  workflow_dispatch:
    inputs:
      start_from_scratch:
        description: "Scratch From Scratch"
        required: false
        default: false
        type: boolean
  schedule:
    - cron: "0 1 1 * *"
  push:
    branches: [master]
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          df -h
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: utrarobosoccer/soccerbot
          cache-from: type=registry,ref=utrarobosoccer/soccerbot
          cache-to: type=inline
