name: Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 1 * *"
  push:
    branches: [master]
    paths-ignore:
      - "**.md"

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          df -h
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive
      # Ensure that the filesystem permissions are consistent across all umasks, all git checkouts:
      - name: Set filesystems permissions
        run: |
          chmod -R g+w .
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: Dockerfile
          build-args: |
            INSTALL_CUDA=true
          tags: utrarobosoccer/soccerbot
          cache-from: type=registry,ref=utrarobosoccer/soccerbot
          cache-to: type=inline
#      - name: Push to AWS repository
#        run: |
#          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          docker pull utrarobosoccer/soccerbot
#          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 047817357099.dkr.ecr.us-east-2.amazonaws.com/hl-vs-utra
#          docker tag utrarobosoccer/soccerbot 047817357099.dkr.ecr.us-east-2.amazonaws.com/hl-vs-utra
#          docker push 047817357099.dkr.ecr.us-east-2.amazonaws.com/hl-vs-utra
