name: Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 1 * *"
  push:
    branches: [master]
    paths:
      - "soccer_localization"

jobs:
  update_subtree:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive
      - name: Update soccer localization subtree
        run: |
          git subtree push --prefix soccer_localization/ git@github.com:utra-robosoccer/soccer_localization.git master
