name: Webots Docker Image CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build the Docker image
        run: docker build external --file external/Dockerfile --tag utrarobosoccer/webots
      - name: Build and push Docker images
        run: docker push utrarobosoccer/webots
